version: '3.5'

services:
  minitwitter:
    build:
      context: .
      dockerfile: MiniTwitPostgres.Dockerfile
    image: minitwit
    environment:
      connection_string: Host=postgres;Port=5432;Database=minitwit;Username=ole;Password=veryhardcode
    ports:
      - "5235:80"
    depends_on:
      - postgres
  simulation:
    container_name: simulation
    build:
      context: .
      dockerfile: SlimTwit.Dockerfile
    image: minitwit-simulation
    environment:
      connection_string: Host=postgres;Port=5432;Database=minitwit;Username=ole;Password=veryhardcode
    ports:
      - "5236:5236"
    depends_on:
      - postgres
      - minitwitter
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=ole
      - POSTGRES_PASSWORD=veryhardcode
      - POSTGRES_DB=minitwit
      # - PGDATA=/data/postgres
      # volumes:
      # - /minitwit.db:/docker-entrypoint-initdb.d/minitwit.db
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf
      # - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
   
  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3000:3000"
  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
  