version: '3.5'

services:
  minitwitter:
    build:
      context: .
      dockerfile: MiniTwitPostgres.Dockerfile
    image: minitwit
    environment:
      connection_string: Host=postgres;Port=5432;Database=minitwit;Username=ole;Password=veryhardcode
    ports:
      - "5235:80"
    depends_on:
      - postgres
  simulation:
    container_name: minitwitmoni
    build:
      context: .
      dockerfile: SlimTwit.Dockerfile
    image: minitwit-simulation
    environment:
      connection_string: Host=postgres;Port=5432;Database=minitwit;Username=ole;Password=veryhardcode
    ports:
      - "5236:80"
    depends_on:
      - postgres
      - minitwitter
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=ole
      - POSTGRES_PASSWORD=veryhardcode
      - POSTGRES_DB=minitwit
      # - PGDATA=/data/postgres
      # volumes:
      # - /minitwit.db:/docker-entrypoint-initdb.d/minitwit.db
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf
      # - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
   
    
    
  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3000:3000"
  