version: '3.5'

services:
  minidev:
    build: 
      context: .
      dockerfile: MiniTwit.Dev.Dockerfile
    image: minitwitdev
    environment:
      connection_string: Host=postgresdev;Port=5432;Database=minitwit;Username=ole;Password=veryhardcode
    ports:
      - "5550:5550"
    depends_on:
      - postgresdev
    volumes:
      - .:/app
  postgresdev:
    container_name: postgresdev
    image: postgres:latest
    environment:
      - POSTGRES_USER=ole
      - POSTGRES_PASSWORD=veryhardcode
      - POSTGRES_DB=minitwit
    ports:
      - "5432:5432"
