version: '3.5'
services:
  minitwitter:
    container_name: minitwit-server
    build:
      context: ./../..
      dockerfile: ./Docker/Dockerfiles/MiniTwitPostgres.Dockerfile
    image: minitwit-server
    environment:
      connection_string: Host=postgres;Port=5432;Database=minitwit;Username=ole;Password=veryhardcode
    ports:
      - "5235:80"
    depends_on:
      - postgres
  simulator:
    container_name: minitwit-simulator
    build:
      context: ./../..
      dockerfile: ./Docker/Dockerfiles/SlimTwit.Dockerfile
    image: minitwit-simulator
    environment:
      connection_string: Host=postgres;Port=5432;Database=minitwit;Username=ole;Password=veryhardcode
    ports:
      - "5236:5236"
    depends_on:
      - postgres
      - minitwitter
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=ole
      - POSTGRES_PASSWORD=veryhardcode
      - POSTGRES_DB=minitwit
    ports:
      - "5432:5432"
