version: '3.5'
# ! ! ! ! ! NOTICE NOTICE NOTICE NOTICE ! ! ! ! !
# This is a development compose file. Use it to test things but never deploy it. 
# Use it to see if everything works together.
# You can use bits from it, but thats about it. The reason for this is:
# 1. The paths a not correct and should be fixed
# 2. We launch to many images where things should be seperated.
# 3. We also launch a postgres database and this should not happen in production.
services:
  minitwitter:
    image: bhviid/devops
    container_name: minitwit
    restart: unless-stopped
    environment:
      connection_string: Host=postgres;Port=5432;Database=minitwit;Username=ole;Password=veryhardcode;
    ports:
      - "5235:80"
    depends_on:
      - postgres
  slimtwitter:
    image: bhviid/slimtwit
    container_name: slimtwit
    restart: unless-stopped
    environment:
      connection_string: Host=postgres;Port=5432;Database=minitwit;Username=ole;Password=veryhardcode;
    ports:
      - "5236:5236"
    depends_on:
      - postgres
      - minitwitter
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=ole
      - POSTGRES_PASSWORD=veryhardcode
      - POSTGRES_DB=minitwit
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
