version: '3.5'

services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      - POSTGRES_USER=ole
      - POSTGRES_PASSWORD=veryhardcode
      - POSTGRES_DB=minitwit
      # - PGDATA=/data/postgres
      # volumes:
      # - /minitwit.db:/docker-entrypoint-initdb.d/minitwit.db
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf
      # - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
