version: '3.5'


services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      - POSTGRES_DB=minitwit
      - POSTGRES_USER=ole
      - POSTGRES_PASSWORD=veryhardcode
      - PGDATA=/data/postgres
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"


½