name: Build LaTeX document
on:
  push:
    branches: [main]
    paths:
      - '/report'
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest    
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./report
          root_file: main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: BSc_group_j
          path: ./report/main.pdf
      - name: Move PDF file
        run: |
          mkdir -p ./report/build
          mv ./report/main.pdf ./report/build/BSc_group_j.pdf
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Updated BSc_group_j.pdf
            file_pattern: './report/build/BSc_group_j.pdf'

