name: Manual deploy to server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: make docker directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP_ADDRESS }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p ~/docker/

    - name: Copy docker-compose.yml to minitwit droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP_ADDRESS }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: /Dockerfiles/minitwit-compose/docker-compose.yml
        target: ~/docker/docker-compose.yml

    - name: Copy prometheus.yml to minitwit droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP_ADDRESS }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: prometheus.yml
        target: ~/docker/prometheus.yml

    - name: SSH into minitwit droplet, do a docker pull and run docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP_ADDRESS }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          connection_string: ${{ secrets.POSTGRES_CONNECTION_STRING }}
        script: |
          sudo ufw allow 3000
          sudo ufw allow 5235
          sudo ufw reload
          docker kill minitwit
          docker rm minitwit
          cd ~/docker
          docker-compose pull && docker-compose up -d
    
    - name: make docker directory for sim droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP_ADDRESS_SIM }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p ~/docker/

    - name: Copy docker-compose.yml to sim droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP_ADDRESS_SIM }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: /Dockerfiles/minitwit-compose/docker-compose.yml
        target: ~/docker/docker-compose.yml

    - name: Copy prometheus.yml to sim droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP_ADDRESS_SIM }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: prometheus.yml
        target: ~/docker/prometheus.yml

    - name: SSH into sim droplet, do a docker pull and run docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP_ADDRESS_SIM }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          connection_string: ${{ secrets.POSTGRES_CONNECTION_STRING }}
        script: |
          sudo ufw allow 3000
          sudo ufw allow 5236
          sudo ufw reload
          docker kill minitwit
          docker rm minitwit
          cd ~/docker
          docker-compose pull && docker-compose up -d
