name: Deploy App

on:
  push:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: bhviid/6489381c3a7a
  DROPLET_USERNAME: your_droplet_username
  DROPLET_IP_ADDRESS: your_droplet_ip_address

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE_NAME .

      - name: Log in to Docker Hub
        run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE_NAME

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DROPLET_IP_ADDRESS }}
          username: ${{ env.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            docker stop mycontainer || true
            docker rm mycontainer || true
            docker pull $DOCKER_IMAGE_NAME
            docker run -d --name mycontainer -p 80:80 $DOCKER_IMAGE_NAME
